version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackthecrous
    ports:
      - 5432:5432
    volumes:
      - htc-db-vol:/var/lib/postgresql/data
  redis:
    image: redis:7.2.3-alpine
volumes:
  htc-db-vol:
