apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}-deployment
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        env:
          - name: CLIENT_URL
            value: {{ .Values.clientUrl | quote }}
          - name: FULL_SERVER_URL
            value: {{ .Values.fullServerUrl | quote }}
          - name: GOOGLE_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.googleAuthSecretName }}
                key: google_auth_secret
          - name: GOOGLE_AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.googleAuthSecretName }}
                key: google_auth_client_id
          - name: HASH_ROUND
            value: {{ .Values.hashRound | quote }}
          - name: PORT
            value: {{ .Values.service.internalPort | quote }}
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.jwtSecretName }}
                key: jwt_secret
          - name: PG_DATABASE
            value: {{ .Values.postgresql.database }}
          - name: PG_HOST
            value: {{ .Values.postgresql.host | quote}}
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.secretName }}
                key: postgresql-password
          - name: PG_PORT
            value: {{ .Values.postgresql.port | quote }}
          - name: PG_USER
            value: {{ .Values.postgresql.username | quote }}
          - name: REDISHOST
            value: {{ .Values.redis.host | quote }}
          - name: REDISPORT
            value: {{ .Values.redis.port | quote }}
          - name: SERVER_URL
            value: {{ .Values.serverUrl | quote }}
          - name: MAIL_SMTP
            value: {{ .Values.mail.mail_address | quote }}
          - name: SMTP_HOST
            value: {{ .Values.mail.smtp_host | quote }}
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mail.secretName }}
                key: mail-password
          - name: SMTP_PORT
            value: {{ .Values.mail.smtp_port | quote }}
          - name: TEMPLATE_PATH
            value: "./template/mail.html"

    