package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"math"
	"time"

	"github.com/Courtcircuits/HackTheCrous.api/api"
	"github.com/Courtcircuits/HackTheCrous.api/graph/model"
	"github.com/Courtcircuits/HackTheCrous.api/types"
	"github.com/Courtcircuits/HackTheCrous.api/util"
	redis "github.com/redis/go-redis/v9"
)

// Restaurants is the resolver for the restaurants field.
func (r *foodResolver) Restaurants(ctx context.Context, obj *model.Food) ([]*model.Restaurant, error) {
	restaurants, err := api.GetServer().Store.GetRestaurantsFromFood(*obj.Names[0])
	if err != nil {
		return nil, err
	}
	var restaurants_gql []*model.Restaurant
	for _, restaurant := range restaurants {
		restaurants_gql = append(restaurants_gql, restaurant.ToGraphQL())
	}
	fmt.Printf("food : %q -> %v\n", *obj.Names[0], restaurants)
	return restaurants_gql, nil
}

// CreateSchool is the resolver for the createSchool field.
func (r *mutationResolver) CreateSchool(ctx context.Context, name *string, coords *string) (*model.School, error) {
	panic(fmt.Errorf("not implemented: CreateSchool - createSchool"))
}

// ModifyUser is the resolver for the modifyUser field.
func (r *mutationResolver) ModifyUser(ctx context.Context, name *string, ical *string, school *int, restaurants []*int) (*model.User, error) {
	gc, err := api.GetGinContext(ctx)
	if err != nil {
		return nil, err
	}
	storage := api.GetServer().Store
	id_user := gc.GetInt("id")
	for _, restaurant_id := range restaurants {
		go storage.AddRestaurantAsFavorite(id_user, *restaurant_id)
	}
	user, err := storage.UpdateUser(id_user, *name, *ical, *school)
	return user.ToGraphQL(), err
}

// ModifyUserBySchoolName is the resolver for the modifyUserBySchoolName field.
func (r *mutationResolver) ModifyUserBySchoolName(ctx context.Context, name *string, ical *string, school *string, restaurants []*int) (*model.User, error) {
	panic(fmt.Errorf("not implemented: ModifyUserBySchoolName - modifyUserBySchoolName"))
}

// Like is the resolver for the like field.
func (r *mutationResolver) Like(ctx context.Context, idrestaurant *int) ([]*model.Restaurant, error) {
	gc, err := api.GetGinContext(ctx)
	if err != nil {
		return nil, err
	}
	id_user := gc.GetInt("id")
	go api.GetServer().Store.AddRestaurantAsFavorite(id_user, *idrestaurant)
	restaurants, err := api.GetServer().Store.GetFavoriteRestaurants(id_user)
	var restaurants_gql []*model.Restaurant
	for _, resto := range restaurants {
		restaurants_gql = append(restaurants_gql, resto.ToGraphQL())
	}
	return restaurants_gql, err
}

// Dislike is the resolver for the dislike field.
func (r *mutationResolver) Dislike(ctx context.Context, idrestaurant *int) ([]*model.Restaurant, error) {
	gc, err := api.GetGinContext(ctx)
	if err != nil {
		return nil, err
	}
	id_user := gc.GetInt("id")
	go api.GetServer().Store.DeleteRestaurantFromFavorite(id_user, *idrestaurant)
	restaurants, err := api.GetServer().Store.GetFavoriteRestaurants(id_user)
	var restaurants_gql []*model.Restaurant
	for _, resto := range restaurants {
		restaurants_gql = append(restaurants_gql, resto.ToGraphQL())
	}
	return restaurants_gql, err
}

// ModifyUserField is the re solver for the modifyUserField field.
func (r *mutationResolver) ModifyUserField(ctx context.Context, name *string, ical *string, school *string, mail *string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: ModifyUserField - modifyUserField"))
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, url *string) (*model.Restaurant, error) {
	restaurant, err := api.GetServer().Store.GetRestaurantByUrl(*url)
	return restaurant.ToGraphQL(), err
}

// Restaurants is the resolver for the restaurants field.
func (r *queryResolver) Restaurants(ctx context.Context) ([]*model.Restaurant, error) {
	var restaurants []*model.Restaurant
	db_restaurants, err := api.GetServer().Store.GetRestaurants()
	if err != nil {
		log.Fatalf("error while getting restaurants in the resolver : %q\n", err)
		return []*model.Restaurant{}, errors.New("500, error while getting restaurants")
	}

	for _, restaurant := range db_restaurants {
		restaurants = append(restaurants, restaurant.ToGraphQL())
	}

	return restaurants, nil
}

// Search is the resolver for the search query
func (r *queryResolver) Search(ctx context.Context, query *string) ([]*model.Restaurant, error) {
	var restaurants []*model.Restaurant
	db_restaurants, err := api.GetServer().Store.SearchRestaurant(*query)
	if err != nil {
		log.Fatalf("error while getting restaurants in the resolver : %q\n", err)
		return []*model.Restaurant{}, errors.New("500, error while getting restaurants")
	}

	for _, restaurant := range db_restaurants {
		restaurants = append(restaurants, restaurant.ToGraphQL())
	}

	return restaurants, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, iduser *int) (*model.User, error) {
	if iduser == nil {
		gc, err := api.GetGinContext(ctx)
		if err != nil {
			return nil, err
		}
		id := gc.GetInt("id")
		iduser = &id
	}
	user, err := api.GetServer().Store.GetUserByID(*iduser)
	return user.ToGraphQL(), err
}

// SearchRestaurant is the resolver for the searchRestaurant field.
func (r *queryResolver) SearchRestaurant(ctx context.Context, query *string) ([]*model.Restaurant, error) {
	var restaurants []*model.Restaurant
	db_restaurants, err := api.GetServer().Store.SearchRestaurantByName(*query)
	if err != nil {
		log.Fatalf("error while getting restaurants in the resolver : %q\n", err)
		return []*model.Restaurant{}, errors.New("500, error while getting restaurants")
	}

	for _, restaurant := range db_restaurants {
		restaurants = append(restaurants, restaurant.ToGraphQL())
	}

	return restaurants, nil
}

// SearchSchool is the resolver for the searchSchool field.
func (r *queryResolver) SearchSchool(ctx context.Context, query *string) ([]*model.School, error) {
	var schools []*model.School
	db_schools, err := api.GetServer().Store.SearchSchoolByName(*query)
	if err != nil {
		log.Fatalf("error while getting restaurants in the resolver : %q\n", err)
		return []*model.School{}, errors.New("500, error while getting restaurants")
	}
	for _, school := range db_schools {
		schools = append(schools, school.ToGraphQL())
	}
	return schools, nil
}

// SearchFood is the resolver for the searchFood field.
func (r *queryResolver) SearchFood(ctx context.Context, query *string) ([]*model.Restaurant, error) {
	//useless to remove from doc i guess
	panic(fmt.Errorf("not implemented: SearchFood - searchFood"))
}

// Day is the resolver for the day field.
func (r *queryResolver) Day(ctx context.Context, date *string) ([]*model.PlanningDay, error) {
	panic(fmt.Errorf("not implemented: Day - day"))
}

// Today is the resolver for the today field.
func (r *queryResolver) Today(ctx context.Context) ([]*model.PlanningDay, error) {
	panic(fmt.Errorf("not implemented: Today - today"))
}

// Period is the resolver for the period field.
func (r *queryResolver) Period(ctx context.Context, start *string, end *string) ([]*model.PlanningDay, error) {
	if start == nil {
		return nil, errors.New("need to define start")
	}
	if end == nil {
		return nil, errors.New("need to define end")
	}
	log.Printf("reading period : %q to %q\n", *start, *end)
	gc, err := api.GetGinContext(ctx)
	if err != nil {
		return nil, err
	}
	id := gc.GetInt("id")
	url_ical, err := api.GetServer().Store.GetCalendarOfUser(id)
	if err != nil {
		return nil, err
	}
	json_calendar, err := api.GetServer().Cache.Get(url_ical)
	var cal types.Calendar
	if err != nil {
		if err == redis.Nil { // ical not cached
			cal, err = types.NewCalendar(url_ical)
			if err != nil {
				return nil, err
			}
			err_chan := make(chan error)
			go api.GetServer().Cache.SetCalendarAsync(cal, err_chan) //set cal in cache asynchronously
			err_async := <-err_chan
			if err_async != nil {
				log.Printf("ERROR while caching calendar : %v", err)
			}
		} else {
			return nil, err
		}
	} else { //if ical is cached
		parsed_cal, err := types.ParseJsonCalendar(json_calendar)
		if err != nil {
			return nil, err
		}
		cal = types.NewCalendarFromJsonCalendar(&parsed_cal)
	}
	start_date, err := time.Parse("02-Jan-2006", *start)
	if err != nil {
		return nil, err
	}
	end_date, err := time.Parse("02-Jan-2006", *end)
	if err != nil {
		return nil, err
	}
	period, err := cal.GetPeriod(start_date, end_date)
	log.Println(period)

	return period, err
}

// GetLatestMail is the resolver for the getLatestMail field.
func (r *queryResolver) GetLatestMail(ctx context.Context) (*model.Mail, error) {
	panic(fmt.Errorf("not implemented: GetLatestMail - getLatestMail"))
}

// GetLatestMails is the resolver for the getLatestMails field.
func (r *queryResolver) GetLatestMails(ctx context.Context, rangeArg *int) ([]*model.Mail, error) {
	panic(fmt.Errorf("not implemented: GetLatestMails - getLatestMails"))
}

// Food is the resolver for the food field.
func (r *queryResolver) Food(ctx context.Context) ([]*model.Food, error) {
	foods, err := api.GetServer().Store.GetFoods()
	if err != nil {
		return nil, err
	}
	var foods_gql []*model.Food
	for _, food := range foods {
		foods_gql = append(foods_gql, food.ToGraphQL())
	}
	return foods_gql, nil
}

// Meals is the resolver for the meals field.
func (r *restaurantResolver) Meals(ctx context.Context, obj *model.Restaurant) ([]*model.Meal, error) {
	meals, err := api.GetServer().Store.GetMealsFromRestaurant(*obj.Idrestaurant)

	var meals_gql []*model.Meal

	for _, meal := range meals {
		meals_gql = append(meals_gql, meal.ToGraphQL())
	}

	return meals_gql, err
}

// Distance is the resolver for the distance field.
func (r *restaurantResolver) Distance(ctx context.Context, obj *model.Restaurant) (*float64, error) {
	gc, err := api.GetGinContext(ctx)

	err_val_inf := math.Inf(1)
	if err != nil {
		return nil, err
	}
	school, err := api.GetServer().Store.GetSchoolOfUser(gc.GetInt("id"))

	if err != nil {
		if err == sql.ErrNoRows {
			return &err_val_inf, errors.New("user school not found")
		} else {
			return &err_val_inf, err
		}
	}

	distance := util.ComputeDistance(school.Coords, util.Coordinates{
		X: *obj.Coords.X,
		Y: *obj.Coords.Y,
	})

	return &distance, nil
}

// Food returns FoodResolver implementation.
func (r *Resolver) Food() FoodResolver { return &foodResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Restaurant returns RestaurantResolver implementation.
func (r *Resolver) Restaurant() RestaurantResolver { return &restaurantResolver{r} }

type foodResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type restaurantResolver struct{ *Resolver }
