default: &default
  host: <%= ENV.fetch("QUICKWIT_HOST") { "localhost" } %>
  port: <%= ENV.fetch("QUICKWIT_PORT") { 7280 } %>
  index_name: <%= ENV.fetch("QUICKWIT_INDEX_NAME") { "restaurants" } %>
  timeout: <%= ENV.fetch("QUICKWIT_TIMEOUT") { 30 } %>

development:
  <<: *default

test:
  <<: *default
  index_name: <%= ENV.fetch("QUICKWIT_INDEX_NAME") { "restaurants_test" } %>

production:
  <<: *default
  host: <%= ENV.fetch("QUICKWIT_HOST") { "quickwit" } %>