name: Image build and push
run-name: ${{ github.actor }} is building and pushing the image of the backend to dockerhub 🚀
on:
  push:
    branches:
      - main

jobs:
  determine_version:
    name: calculate version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gitversion.outputs.semver }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install gitversion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionspec: "6.x"
          includeprerelease: true
      - name: determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  push_to_registry:
    if: >
      contains(github.event.head_commit.message, 'release')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: determine_version
    env:
      TAG: ${{ needs.determine_version.outputs.tag }}
    outputs:
      tag: ${{ needs.determine_version.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: milou666/${{ secrets.DOCKER_IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            milou666/${{ secrets.DOCKER_IMAGE_NAME }}:latest
            milou666/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    if: >
      contains(github.event.head_commit.message, 'release')
    name: deploy_project
    runs-on: ubuntu-latest
    needs: push_to_registry
    env:
      TAG: ${{ needs.push_to_registry.outputs.tag }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Update values.yaml
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
          cd helm
          yq eval -i '.image.tag = env(TAG)' tag.yaml
          git config --global user.name "CI deployment"
          git config --global user.email "ci.deployment.hackthecrous@users.noreply.github.com"
          git add tag.yaml
          git commit -m "${{ env.TAG }} | ${{ github.event.head_commit.message }}"
          git push
